# Generated by Django 6.0.5 on 2026-05-21 10:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(help_text='Unique bus registration/route number', max_length=20, unique=True)),
                ('bus_name', models.CharField(help_text='Bus operator/company name', max_length=100)),
                ('bus_type', models.CharField(choices=[('AC', 'A/C Deluxe'), ('NON_AC', 'Non A/C'), ('SLEEPER', 'Sleeper'), ('SEMI_SLEEPER', 'Semi Sleeper'), ('VOLVO', 'Volvo'), ('TATA', 'Tata'), ('MINI', 'Mini Bus')], default='AC', help_text='Type/category of bus', max_length=20)),
                ('departure_city', models.CharField(db_index=True, max_length=100)),
                ('destination_city', models.CharField(db_index=True, max_length=100)),
                ('departure_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(default='8 hours', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per seat in NPR', max_digits=10)),
                ('total_seats', models.PositiveIntegerField(default=40, help_text='Total seat capacity', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(60)])),
                ('available_seats', models.PositiveIntegerField(default=40)),
                ('amenities', models.TextField(blank=True, help_text='Amenities separated by commas')),
                ('pickup_point', models.CharField(blank=True, max_length=200)),
                ('dropoff_point', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Buses',
                'ordering': ['departure_date', 'departure_time'],
                'indexes': [models.Index(fields=['departure_city', 'destination_city', 'departure_date'], name='booking_bus_departu_3ca6a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Bus photo (uploaded to media/buses/)', upload_to='buses/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='Set as main/display image for the bus')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(help_text='The bus this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.bus')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(help_text='Unique flight number (e.g., RA-101)', max_length=20, unique=True)),
                ('airline', models.CharField(help_text='Airline name (e.g., Buddha Air, Yeti Airlines)', max_length=100)),
                ('flight_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('INTERNATIONAL', 'International')], default='DOMESTIC', max_length=15)),
                ('departure_city', models.CharField(db_index=True, max_length=100)),
                ('destination_city', models.CharField(db_index=True, max_length=100)),
                ('departure_date', models.DateField(db_index=True)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('duration', models.CharField(default='1 hour', max_length=30)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per seat in NPR', max_digits=10)),
                ('total_seats', models.PositiveIntegerField(default=120, help_text='Total seat capacity', validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(300)])),
                ('available_seats', models.PositiveIntegerField(default=120)),
                ('terminal', models.CharField(blank=True, help_text='Airport terminal', max_length=50)),
                ('gate', models.CharField(blank=True, help_text='Boarding gate', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Flights',
                'ordering': ['departure_date', 'departure_time'],
                'indexes': [models.Index(fields=['departure_city', 'destination_city', 'departure_date'], name='booking_fli_departu_351527_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_reference', models.CharField(help_text='Unique booking reference number', max_length=50, unique=True)),
                ('booking_type', models.CharField(choices=[('BUS', 'Bus'), ('FLIGHT', 'Flight')], help_text='Type of transport booked', max_length=10)),
                ('passenger_name', models.CharField(max_length=100)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('passenger_phone', models.CharField(max_length=15)),
                ('passenger_age', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('passenger_gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('seat_number', models.CharField(max_length=10)),
                ('number_of_seats', models.PositiveIntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', help_text='Current status of the booking', max_length=15)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who made this booking', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bus', models.ForeignKey(blank=True, help_text='Bus if this is a bus booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_set', to='booking.bus')),
                ('flight', models.ForeignKey(blank=True, help_text='Flight if this is a flight booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_set', to='booking.flight')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
        migrations.CreateModel(
            name='FlightImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='flights/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='booking.flight')),
            ],
            options={
                'ordering': ['-is_primary', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('KHALTI', 'Khalti'), ('ESEWA', 'eSewa')], help_text='Dummy payment gateway used', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(help_text='Simulated transaction reference', max_length=100, unique=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('booking', models.OneToOneField(help_text='Booking this payment is for', on_delete=django.db.models.deletion.CASCADE, to='booking.booking')),
            ],
            options={
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['booking_reference'], name='booking_boo_booking_189209_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['user', 'status'], name='booking_boo_user_id_dddf68_idx'),
        ),
    ]
